Checks if apikey or appid exist in config array and throws exception …
algolia/algoliasearch-client-php pull request #633
Opened 2020-07-10 11:55 UTC by florian25686

…before contacting algolia

| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no    
| BC breaks?        | no     
| Related Issue     | Fix #...  
| Need Doc update   | no

## Describe your change

Check if required api settings (apikey and appid) are given in the config array or throw an exception.

## What problem is this fixing?

If an api call is made with missing config information it retries multiple times and then fails with an exception. This generates not needed traffic and causing wait times for users.
This change handels the missing information before making changes and throwing an exception if the information are missing

2020-07-10 12:14 UTC, nunomaduro commented
How did you create an instance of the client so you could have that error? Can you send me the code snippet?

2020-07-10 15:44 UTC, florian25686 commented
I followed the tutorial for laravel implementation and set the values in the .env-file. To test what happens if there is a problem with algolia, I set the `appId` to an empty string in my .env-file.

2020-07-21 14:55 UTC, florian25686 commented
Hi @chloelbn,

who is maintaining this client in the future?
Any chance someone from algolia can follow up with this issue?

Best regards,
Florian

2020-07-21 15:02 UTC, chloelbn commented
Hi @florian25686,

I am one the maintainer of this client. We still have to review your PR but it will be done ASAP :) Thanks for your patience!

2020-08-17 12:32 UTC, chloelbn commented on src/SearchClient.php
> +            throw new UnreachableException('Missing config: AppId or AppKey. Please check your settings');
`Missing config: appId or apiKey. Please check your settings`

2020-08-18 07:28 UTC, florian25686 commented on src/SearchClient.php
> +            throw new UnreachableException('Missing config: AppId or AppKey. Please check your settings');
Thank you for the input, I've made the requested change

2020-08-19 07:58 UTC, chloelbn commented
@florian25686 Could you add some tests and fix the ones that broke as well? Thanks a lot!

2020-08-19 07:58 UTC, chloelbn requested changes

2020-08-19 07:58 UTC, chloelbn commented on src/SearchClient.php
> +            throw new UnreachableException('Missing config: appId or apiKey. Please check your settings');
could you throw a `\InvalidArgumentException` here instead of `UnreachableException`?

2020-09-02 12:45 UTC, closed without merging