Fixes #624
algolia/algoliasearch-client-php pull request #637
Opened 2020-08-04 17:39 UTC by joshuabaker

| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | no 
| BC breaks?        | no     
| Related Issue     | Fix #624
| Need Doc update   | no

Please reference [the issue](https://github.com/algolia/algoliasearch-client-php/issues/624) for a description.

Maintainers, I suspect there may be a better home for the `serializeQueryParameters` method. Looking at the JavaScript client, [the like-for-like method](https://github.com/algolia/algoliasearch-client-javascript/blob/e6dec843932bdfaac13ffa1e0a11964975499078/packages/transporter/src/serializer.ts#L22-L36) is used in a few different places.

2020-08-04 19:37 UTC, joshuabaker commented
Guessing this is a version target getting missed?

Please review `serializeQueryParameters` and let me know your thoughts, and I can adjust for PHP compatibility.

2020-08-19 08:24 UTC, chloelbn commented
Hi @joshuabaker! Thanks for your contribution! Your fix looks good but before anything would you mind indeed fixing the PHP compatibility? We have to support PHP 5.6. Also would you mind adding some tests please?

As for where to put `serializeQueryParameters`, I'm okay if you put it in the functions.php file

2020-10-26 16:08 UTC, chloelbn requested changes

2020-10-26 16:08 UTC, chloelbn commented on src/SearchClient.php
> +        $queries = array_map(function($query) {
Would you mind adding some tests, and fix the syntax for older PHP versions please?

2021-04-23 13:15 UTC, chloelbn commented
I'm closing this PR as it's been out of the scope for too long. If the feature is still needed please open a new one 🚀

2021-04-23 13:15 UTC, closed without merging