fix(restore-api-key): fixes flaky tests
algolia/algoliasearch-client-php pull request #641
Opened 2020-09-21 09:07 UTC by chloelbn

| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no     
| Related Issue     | Fix #634
| Need Doc update   | no

## Describe your change

Fixes tests to skip the 429 error

2020-09-21 11:58 UTC, DevinCodes approved these changes

2020-09-21 12:01 UTC, DevinCodes requested changes

2020-09-21 12:01 UTC, DevinCodes commented on tests/Integration/PersonalizationStrategyTest.php
> +        } catch (\Exception $e) {
Can we catch an `AlgoliaException` here instead of the more generic `\Exception`?

2020-09-22 06:44 UTC, DevinCodes approved these changes

2020-09-22 06:45 UTC, DevinCodes commented
Code looks good to me, so I approved ✅  
The CI is failing by the way, any idea why?

2020-09-22 07:37 UTC, chloelbn commented
@DevinCodes fixed the issue!

2020-09-22 09:28 UTC, DevinCodes approved these changes

2020-09-22 14:12 UTC, merged