PHP 8 Support
algolia/algoliasearch-client-php pull request #644
Opened 2020-11-03 12:11 UTC by driesvints

| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | yes    
| BC breaks?        | no     
| Related Issue     | Fix #...  
| Need Doc update   | no

## Describe your change

This PR will provide PHP 8 Support for the library. Atm this is blocking https://github.com/laravel/scout/pull/425

I'll keep the PR in draft until I've fixed the build.

2020-11-03 17:08 UTC, julienbourdeau commented
Thanks Dries!
Was it enough to run it on PHP 8 locally?

2020-11-03 20:05 UTC, driesvints commented
@julienbourdeau I'll need to verify that on thursday

2020-11-04 01:28 UTC, devdreamsolution submitted a review, later dismissed

2020-11-16 16:44 UTC, driesvints commented
@julienbourdeau I wasn't able to get things running on PHP 8 I'm afraid. I think it's best that we get rid of the PHP CS Fixer dependency as soon as you can. Or at least find a way how we can add `--ignore-platform-req=php` to the nightly build.

2020-11-17 08:57 UTC, julienbourdeau commented
I think removing php-cs-fixer in the deps should be fine. It's only needed in the CI anyway

2020-11-17 11:20 UTC, driesvints commented
I'm gonna wait a bit with proceeding here until the CircleCI PR has been merged so I can rebase on it.

2020-11-25 10:01 UTC, chloelbn commented
@driesvints circleCI has been merged on master! you can keep going. Thanks for your work!

2020-11-26 08:21 UTC, driesvints commented
Seems like builds for forked PRs aren't enabled yet: https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories

2020-11-26 09:51 UTC, chloelbn commented
@driesvints Nice catch thanks! it should be good now

2020-11-26 10:11 UTC, julienbourdeau commented on CHANGELOG.md
> +
```suggestion


```

2020-11-26 10:15 UTC, julienbourdeau commented on composer.json
> +        "phpunit/phpunit": "^4.8 || ^9.3",
```suggestion
        "phpunit/phpunit": "^4.8",
```

2020-11-26 10:17 UTC, julienbourdeau commented
PHP 8.0 doesn't seem available on circle-ci yet: `Error response from daemon: manifest for circleci/php:8.0 not found`.

Our tests were written for PHPUnt 4 and won't work with PHPUnit 9 unfortunately.

2020-11-26 10:31 UTC, chloelbn commented
@julienbourdeau luckily for us, as implementing the CTS is in our pipeline we'll be able to upgrade PHPUnit as well too, right?

2020-11-26 10:38 UTC, julienbourdeau commented
@chloelbn Unfortunately, PHPUnit 9 is only compatible with recent php version. And since there are breaking change, you can't have one test suite that works in old PHPUnit and newer PHPUnit 😬 
Not sure how we're going to deal with it yet 😩

2020-11-26 10:42 UTC, driesvints commented
@julienbourdeau pushed a change to name the builds. They now appear much more readable here in the GitHub checks overview.

We'll need to provide a matrix for the PHPUnit versions.

2020-11-26 10:53 UTC, chloelbn requested changes

2020-11-26 10:53 UTC, chloelbn commented on tests/tests-no-composer.php
> +    return sprintf(
this fix seems to make the CI fail

2020-11-26 14:37 UTC, chloelbn requested changes

2020-11-26 14:37 UTC, chloelbn commented on tests/tests-no-composer.php
> +        getenv('CI_BUILD_NUM') ? 'TRAVIS_php_%s_%s_%s' : 'php_%s_%s_%s',
```suggestion
        getenv('CI_BUILD_NUM') ? 'CIRCLE_php_%s_%s_%s' : 'php_%s_%s_%s',
```

2020-11-26 14:39 UTC, chloelbn commented
@driesvints @julienbourdeau I'm not sure we want to provide a matrix for the PHPUnit version. I fear it will crowd up the queue in the CI. Defining it in `composer.json` is enough IMO. WDYT?

2020-11-26 14:58 UTC, driesvints commented
Sure, as long as PHPUnit 4 tests pass on PHP 8. We just need to figure out on how to get a working build for that now. Probably needs a different Docker image.

2020-11-29 15:51 UTC, driesvints commented
Converted back to draft until we can test on PHP 8.

CircleCI is providing support for this soon it seems: https://github.com/CircleCI-Public/cimg-php/pull/96

2020-11-30 19:24 UTC, felicianotech commented
The CircleCI PHP 8 image (`cimg/php:8.0.0`) is now ready.

2020-12-01 10:01 UTC, driesvints commented
@felicianotech thanks. Isn't there a "latest" tag like on circleci/php?

2020-12-01 10:43 UTC, driesvints commented
Okay I've managed to get the builds working properly now. I've migrated everything to cimg/php except for the 7.0 build for which there isn't a tag on cimg/php. 

I'm currently stuck at this error:

```
PHP Fatal error:  Uncaught Algolia\AlgoliaSearch\Exceptions\BadRequestException: Index not allowed with this API key in /home/circleci/project/src/RetryStrategy/ApiWrapper.php:219
Stack trace:
#0 /home/circleci/project/src/RetryStrategy/ApiWrapper.php(167): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->handleResponse()
#1 /home/circleci/project/src/RetryStrategy/ApiWrapper.php(101): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->request()
#2 /home/circleci/project/src/SearchIndex.php(111): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->write()
#3 /home/circleci/project/tests/tests-no-composer.php(12): Algolia\AlgoliaSearch\SearchIndex->setSettings()
#4 {main}
  thrown in /home/circleci/project/src/RetryStrategy/ApiWrapper.php on line 219
```

It seems there's something wrong with the Algolia keys but I'm not sure what. Can any of you figure that one out?

In the meantime, the PHP 8 build is running well but it's failing because of an old PHPUnit version: 

```
PHP Fatal error:  Uncaught Error: Call to undefined function each() in /home/circleci/project/vendor/phpunit/phpunit/src/Util/Getopt.php:38
Stack trace:
#0 /home/circleci/project/vendor/phpunit/phpunit/src/TextUI/Command.php(240): PHPUnit_Util_Getopt::getopt()
#1 /home/circleci/project/vendor/phpunit/phpunit/src/TextUI/Command.php(111): PHPUnit_TextUI_Command->handleArguments()
#2 /home/circleci/project/vendor/phpunit/phpunit/src/TextUI/Command.php(100): PHPUnit_TextUI_Command->run()
#3 /home/circleci/project/vendor/phpunit/phpunit/phpunit(52): PHPUnit_TextUI_Command::main()
#4 {main}
  thrown in /home/circleci/project/vendor/phpunit/phpunit/src/Util/Getopt.php on line 38
```

2020-12-01 10:54 UTC, driesvints commented
PHPUnit 8.5/9.4 is failing on the void return type as I expected. This leaves us with two options. Either drop everything below PHP 7 or duplicate the test suite for older PHP versions. A third option is to not build on PHP 5.4 anymore.

2020-12-01 11:03 UTC, driesvints commented
There's a fourth option we can take maybe. PHP Webdriver patches their tests for newer PHPUnit versions with this script: https://github.com/php-webdriver/php-webdriver/pull/828/files#diff-bde422e37af67712869f8827f3dbc90538ab9fe13556cf32bd6d3997ba05ca4aR1-R20

We could do the same and then we'd at least be able to see what fails on PHP 8.

2020-12-01 11:17 UTC, driesvints commented
A fifth option which is maybe a very reasonable one is to create a new package for this client where you only support modern PHP versions. That's a very reasonable choice given that we're currently only blocked by the test suite. The new package could support PHP 7.2 and up?

2020-12-01 11:22 UTC, driesvints commented
I found even a sixth option by advice from @crynobone. We could look into adoption https://github.com/Yoast/PHPUnit-Polyfills maybe instead of PHPUnit.

2020-12-03 16:35 UTC, chloelbn commented
@driesvints about the index name error, you have to revert the renaming of the `safeName()` method like so
```
function safeName($name)
{
    if (getenv('CI_BUILD_NUM')) {
        return sprintf('php_%s_%s', $name, getenv('CI_BUILD_NUM'));
    }

    return $name;
}
```

We're considering indeed releasing a new major that could drop the older PHP versions. In the meantime however, could you try out option #4 (I really thank you for all the research you're going on this matter!) and see how it works out? it would seem the cleaner short-term solution

2020-12-04 11:33 UTC, driesvints commented
Hey @chloelbn. I've reverted the changes to the `safeName` method but the builds still seems to fail: https://app.circleci.com/pipelines/github/algolia/algoliasearch-client-php/97/workflows/1e1a9d2e-c7b8-40e3-85bd-a50edc66b250/jobs/460

2020-12-08 23:56 UTC, thadbryson commented
PHP-CS-Fixer added PHP 8 support in version 2.17.0 so that shouldn't be a blocker anymore. 

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.17/composer.json

2020-12-10 05:34 UTC, thadbryson commented
I added my own pull request to get unit tests to work. I bumped PHPUnit to ^9.3.

2020-12-10 14:31 UTC, driesvints commented
@chloelbn I've tried implementing the script but now the tests are failing on PHP because the old state of the tests don't work on newer PHPUnit versions anymore: https://app.circleci.com/pipelines/github/algolia/algoliasearch-client-php/104/workflows/2f529bfb-a235-402b-afb3-59454828a064/jobs/531

https://github.com/Yoast/PHPUnit-Polyfills seems like an alternative but requires the entire test suite to be rewritten as PHPUnit 9 tests.

At this point I'd suggest to create a separate 2.x branch from master which contains the current v2 releases and do a new v3 major version on master (or separate 3.x branch) which drops everything below PHP 7.2. It's the most viable choice because supporting all these PHP versions in a single branch just isn't feasible or maintainable.

2020-12-10 14:34 UTC, thadbryson commented
> @chloelbn I've tried implementing the script but now the tests are failing on PHP because the old state of the tests don't work on newer PHPUnit versions anymore: https://app.circleci.com/pipelines/github/algolia/algoliasearch-client-php/104/workflows/2f529bfb-a235-402b-afb3-59454828a064/jobs/531
> 
> https://github.com/Yoast/PHPUnit-Polyfills seems like an alternative but requires the entire test suite to be rewritten as PHPUnit 9 tests.
> 
> At this point I'd suggest to create a separate 2.x branch from master which contains the current v2 releases and do a new v3 major version on master (or separate 3.x branch) which drops everything below PHP 7.2. It's the most viable choice because supporting all these PHP versions in a single branch just isn't feasible or maintainable.

I agree. They'll have to drop support for PHP 5 and stick with 7.1 and higher. Maintaining both is not feasible.

2020-12-16 17:29 UTC, asivaneswaran commented
Just wondering if there was any ETA on this?

This is kinda blocking me to move my project to 8.0.

Thanks

2020-12-16 18:34 UTC, lahivee commented
It really isn't a plus for Algolia to fail keeping their repositories up2date even 3 weeks (!) after the latest PHP release.

2020-12-22 01:28 UTC, thadbryson commented
I encourage everyone who wants Algolia to bump support to PHP 8.0 to contact them. 

https://www.algolia.com/support/

Currently their documention says they support everything at and above 5.3 which is no longer accurate.

2020-12-22 09:26 UTC, chloelbn commented
@thadbryson please do not reach out for support, we have to be mindful of their time while the dedicated API client team is already actively working on this matter. We'll soon be able to merge [this PR](https://github.com/algolia/algoliasearch-client-php/pull/656) from @julienbourdeau.

Indeed a new major is required and we're preparing it as we speak, but to make all the changes required it won't be ready before a few weeks. We'll deliver a quick fix in the meantime through the previous PR so that our client won't be in your way anymore to upgrade to PHP 8.

Thanks for your patience and your understanding 💖

2020-12-22 11:33 UTC, chloelbn commented
PHP 8 support has been added to the latest patch version, `2.7.3` 🎉 
I'm closing this PR, thanks a lot @driesvints and everyone else for your work! A new major version is in the pipeline, but for the moment we hope that this new version will help you move forward in your own projects! Please let us know if you encounter any issues.

Cheers!

2020-12-22 11:33 UTC, closed without merging

2020-12-22 11:44 UTC, driesvints commented
Thanks @chloelbn & @julienbourdeau 👍

2020-12-22 14:01 UTC, asivaneswaran commented
Great news, thanks everyone involved!

@chloelbn @driesvints @julienbourdeau

2020-12-22 14:28 UTC, arcticlinux commented
Thanks everyone!

On Tue., Dec. 22, 2020, 7:01 a.m. asivaneswaran, <notifications@github.com>
wrote:

> Great news, thanks everyone involved!
>
> @chloelbn <https://github.com/chloelbn> @driesvints
> <https://github.com/driesvints> @julienbourdeau
> <https://github.com/julienbourdeau>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/algolia/algoliasearch-client-php/pull/644#issuecomment-749554221>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAXOLZAKBAW7EJERXBQAGTSWCRDTANCNFSM4TIVH3LA>
> .
>