Setup Circle CI
algolia/algoliasearch-client-php pull request #646
Opened 2020-11-04 17:16 UTC by julienbourdeau

This PR moves the CI from Travis to CircleCI.

We're not going to test the client against PHP 5.3 anymore. Running such an old version of PHP is basically impossible today.

It runs against:

- [x] PHP 5.6
- [x] PHP 7.0
- [x] PHP 7.4
- [x] PHP _latest_ (7.4 today but it's going to be 8.0 very soon)

2020-11-04 19:52 UTC, chloelbn requested changes

2020-11-04 19:52 UTC, chloelbn commented on .circleci/config.yml
> +workflows:
Could you run the tests with Guzzle 6, 7 and the basic curl http requester please?

2020-11-05 07:47 UTC, julienbourdeau commented on .circleci/config.yml
> +workflows:
Damit I forgot about that ! Yes, thank you 👍

2020-11-09 14:05 UTC, chloelbn commented on .circleci/config.yml
> +              export CI_PROJ_REPONAME=$CIRCLE_PROJECT_REPONAME
what are those two variables used for?

2020-11-16 16:20 UTC, julienbourdeau commented on .circleci/config.yml
> +              export CI_PROJ_REPONAME=$CIRCLE_PROJECT_REPONAME
For the API Key Dealer client, in order to generate the correct payload

2020-11-25 06:33 UTC, julienbourdeau commented
PHP 8 is going to be released tomorrow.

I'm merging this to help testing on PHP 8. Since Travis is failing all over the place, it can only be better anyway.

Please let me know if there are any other change you'd like me to do.

2020-11-25 06:33 UTC, merged