Add Algolia CTS
algolia/algoliasearch-client-php pull request #665
Opened 2021-02-04 16:27 UTC by damcou

This PR changes the Test Suite and make it compliant with the Algolia CTS.

2021-02-08 15:03 UTC, chloelbn requested changes

2021-02-09 13:12 UTC, chloelbn requested changes

2021-02-09 13:12 UTC, chloelbn commented on tests/Integration/InsightsClientTest.php
> +        self::assertEquals(200, $response['status']);
could you use the `$this->assertEquals` notation instead?

2021-02-09 13:40 UTC, damcou commented on tests/Integration/BaseTest.php
> +        static::$indexes = array();
It comes from the original class : https://github.com/algolia/algoliasearch-client-php/blob/master/tests/Integration/AlgoliaIntegrationTestCase.php#L22

To be honest, I don't fully know why it's there, I chose to keep it but I guess it's not mandatory

2021-02-10 09:26 UTC, chloelbn commented on tests/Integration/BaseTest.php
> +        static::$indexes = array();
Yup, we can delete it! thanks

2021-02-10 14:35 UTC, chloelbn requested changes

2021-02-10 14:35 UTC, chloelbn commented on tests/Integration/AccountTest.php
> +    protected static $secondaryIndexes = array();
you can remove the `static` type now that you don't delete the indexes anymore

2021-02-10 14:35 UTC, chloelbn commented on tests/Integration/AccountTest.php
> +        static::$indexes['copy_index'] = TestHelper::getTestIndexName('copy_index');
same here, they can be called within the class

2021-02-10 14:35 UTC, chloelbn commented on tests/Integration/AccountTest.php
> +        $copyIndex = TestHelper::getClient()->initIndex(static::$indexes['copy_index']);
after making that change you'll be able to add the index directly in the indexes arrays and call `getIndexName()` to retrieve the name of each index anytime you'll need it

2021-02-10 16:57 UTC, chloelbn requested changes

2021-02-10 16:57 UTC, chloelbn commented on tests/Integration/RecommendationClientTest.php
> +        $recommendationClient->setPersonalizationStrategy($strategy);
you can delete this part

2021-02-10 17:01 UTC, chloelbn requested changes

2021-02-10 17:01 UTC, chloelbn commented on tests/Integration/SearchClientTest.php
> +            'indexes' => array('index'),
maybe that'd be worth here to use a safe index name as so to avoid duplication with other test suite

2021-02-10 17:32 UTC, DevinCodes submitted a review, later dismissed
Awesome job on this! I just have a few comments, but it looks great 💯

2021-02-10 17:32 UTC, DevinCodes commented on tests/Integration/AccountTest.php
> +        }
Same comment as before

2021-02-10 17:32 UTC, DevinCodes commented on tests/Integration/AnalyticsClientTest.php
> +        }
Same comment as earlier

2021-02-10 17:32 UTC, DevinCodes commented on tests/Integration/AnalyticsClientTest.php
> +        }
Same comment as earlier

2021-02-10 17:32 UTC, DevinCodes commented on tests/TestHelper.php
> +        }
We don't have to check if a key is set when using `unset`, and we can `unset` multiple keys in one call 🙂 
```suggestion
        unset($rule['_metadata'], $rule['_highlightResult']);
```

2021-02-10 17:32 UTC, DevinCodes commented on tests/Integration/SecuredApiKeysTest.php
> +        }
Same comment as earlier

2021-02-10 17:32 UTC, DevinCodes commented on tests/Integration/RecommendationClientTest.php
> +        }
Same comment as earlier

2021-02-11 08:56 UTC, chloelbn commented on tests/Integration/AccountTest.php
> +        }
the thind is that this portion of code would then need to be extracted to its own function, whereas for the CTS we favour the approach of having all test in the same method

2021-02-11 09:38 UTC, DevinCodes commented on tests/Integration/AccountTest.php
> +        }
Sorry, I mentioned the `expectsException` methods, but that's in another PHPUnit version. We can use the `setExpectedException` method. I can do the following in the same method without affecting the other assertions, so there doesn't seem to be a need to extract it into its own function:

```
$this->setExpectedException('\InvalidArgumentException', 'If both index are on the same app, please use SearchClient::copyIndex method instead.');
AccountClient::copyIndex($copyIndex, $secondaryIndex)->wait();
```

2021-02-11 12:54 UTC, damcou commented on tests/Integration/AccountTest.php
> +        }
Hi @DevinCodes , from what I can see, doing things like this works but it stops the current test (so all the next tests afterwards are skipped), Am I doing something wrong ?

2021-02-11 13:09 UTC, DevinCodes commented on tests/Integration/AccountTest.php
> +        }
Ah you're right, I'm seeing the same thing now indeed. My bad, let's keep the `try/catch` block then!

2021-02-16 12:38 UTC, chloelbn approved these changes

2021-02-16 12:38 UTC, merged