feat(recommend): add RecommendClient class
algolia/algoliasearch-client-php pull request #686
Opened 2021-08-25 16:04 UTC by damcou

| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no     
| Need Doc update   | yes

## Describe your change

This PR introduces the Recommend Client implementation

2021-08-30 11:08 UTC, DevinCodes requested changes
I just have some nitpicks, but overall this looks great! 👌

2021-08-30 12:18 UTC, DevinCodes requested changes
Can you fix the linting errors, please? 🙂

2021-08-30 12:28 UTC, damcou commented
> Can you fix the linting errors, please? 🙂

Oops sorry, I thought it was flakiness issues :p

2021-08-30 12:37 UTC, DevinCodes commented
> > Can you fix the linting errors, please? 🙂
> 
> Oops sorry, I thought it was flakiness issues :p

It is now 💀

2021-08-30 12:41 UTC, DevinCodes requested changes
One last thing, the rest looks good to me! 🚀

2021-08-30 12:41 UTC, DevinCodes commented on tests/Integration/RecommendClientTest.php
> +                'model' => 'bought-together',
Can you refactor these occurrences to use the constants you've introduced, please? This will make refactoring easier later on.

2021-08-30 14:14 UTC, DevinCodes requested changes
This is the last one, promise! 😄  Could you update the usage of the constant as well, please? Thank you!

2021-08-30 14:14 UTC, DevinCodes commented on src/RecommendClient.php
> +    const RELATED_PRODUCT = 'related-products';
```suggestion
    const RELATED_PRODUCTS = 'related-products';
```

2021-08-30 14:19 UTC, damcou commented on src/RecommendClient.php
> +    const RELATED_PRODUCT = 'related-products';
Sorry for that :(

2021-08-31 08:34 UTC, DevinCodes approved these changes

2021-08-31 08:46 UTC, merged